require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

workspace 'influencity'

target 'influencity' do
  # Install additional dependencies
  pod 'Firebase/Core', '~> 6.7.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  target 'influencityTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1'})

  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end


    # # REMOVE ALL WEB VIEWS
    # react_project = Xcodeproj::Project.open("../node_modules/react- 
    # native/React/React.xcodeproj")
    # react_project.main_group["React/Views"].files.each do |file|
    #   if file.path.match(/^RCTWebView/)
    #     file.remove_from_project
    #   end
    # end
    # react_project.save
  end
end

target 'influencity-tvOS' do
  # Pods for influencity-tvOS

  target 'influencity-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

